version: 8.0.3.{build}
os: Visual Studio 2015
init:
- git config --global core.autocrlf true
test: off
build_script:
- cmd: build.cmd ci
artifacts:
  - path: './bin/unity/*.unitypackage'
    name: UnityPackage
cache:
- packages -> **\packages.config
